"""empty message

Revision ID: 273797912830
Revises: af40aed19ef0
Create Date: 2025-03-10 01:58:31.733827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273797912830'
down_revision = 'af40aed19ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('total_detections', sa.Integer(), nullable=False),
    sa.Column('detected_objects', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uav_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('detection_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('detection_type')
        batch_op.drop_column('image_path')

    op.drop_table('uav_status')
    op.drop_table('report')
    op.drop_table('notification')
    # ### end Alembic commands ###
