"""Add foreign key relationships between Drone and Mission

Revision ID: 59c4b72eacce
Revises: f465d7ae94ca
Create Date: 2025-04-10 00:29:17.678826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c4b72eacce'
down_revision = 'f465d7ae94ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mission', ['last_mission_id'], ['id'])

    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'drone', ['drone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('drone_id')

    with op.batch_alter_table('drone', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
