"""Add detected_objects to mission table

Revision ID: b2e6149455bc
Revises: 247276dfb2aa
Create Date: 2025-04-23 17:20:32.310340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e6149455bc'
down_revision = '247276dfb2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_objects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('detected_objects')

    # ### end Alembic commands ###
